### ISSUE TITLE
Error while trying to install from Chaotic-AUR rep

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [arch-linux-gui/arch-linux-gui#1]
So i discovered about your project online and everything went smooth and cool until i started to install packs from AUR, i started to get errors about PGP Keys
```
Error: brave: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is unknown trust 
Error: Failed to commit transaction: invalid or corrupted package (PGP signature): 

```
and i searched online and no luck so i kept reinstall (inside VM) and still no luck until i posted it on reddit https://www.reddit.com/nouqxe and the solution was to import the keys of `Chaotic-AUR` repo (keying of Chaotic-AUR) so i think it's a distro problem? i'm not sure it might be only so i ask you to check if its in distro itself so you fix it in next update or even mention this problem in the readme file? so yeah let me know i made the ticket to make sure it's not distro-wide bug

**Comment by EsmailELBoBDev2** [comment]
Again might be my distro only but while i was trying to run VirtualBox i got errors about linux headers are not installed and for newbie like me in arch world i really struggled to solve it so if you can mention it in your readme file or pre-install it too the `linux-headers` package it really would be nice

**Comment by arch-linux-gui** [comment]
Hi, Thanks for pointing these things out. I will take note of these in future releases. 

If you are still running the May release which has Chaotic Repo, you need to add the new key as the chaotic packages were removed from the AUR.

Copy and paste this into the terminal:
` sudo pacman-key --recv-key 3056513887B78AEB`
and then
`sudo  pacman-key --lsign-key 3056513887B78AEB`

I have removed Chaotic Repo in the June release and replaced it with Paru. The themed editions include base-devel, pacman-contrib and paru, so you just `paru -S` for an AUR packager and `paru -Ss` to search for a package in the AUR.

Sorry for replying so late, this only came to my attention right now.

**Comment by arch-linux-gui** [comment]
linux-headers and base-devel now come pre-installed in the themed editions.
